steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud app deploy --account=automated-build-account@berkheiser-cis693.iam.gserviceaccount.com ./source/app.yaml']
  timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY